Fix doctests using cabal-doctest
haskell/random pull request #128
Opened 2022-03-08 00:00 UTC by ysangkok

Tested using

    cabal test doctests --enable-tests -w ghc-8.4.4

I have changed the mechanism used to disable these test to using `buildable: False`
instead of making the test just quit. That way, the user won't be misled
into thinking that the tests were actually run.

2022-03-08 00:09 UTC, ysangkok commented
Oops, I did the rebase wrong, it is now fixed @lehins .

2022-03-08 08:56 UTC, lehins requested changes
I understand what your motivation is, but making doctests non buildable for ghc versions that don't support doctests simply complicates CI, without any real benefit for maintainers. In other words I am against this change, because doctests are primarily there for maintainers to ensure examples in the haddock haven't been broken. 

Thank you for your attempt though

2022-03-08 08:56 UTC, lehins commented on random.cabal
> +   cabal-doctest >= 1 && <1.1
Why do you need cabal-doctest? It has been deprecated (see hackage)

2022-03-08 08:56 UTC, lehins commented on Setup.hs
> +main = defaultMainWithDoctests "doctests"
Custom set up with cabal-doctest has not been necessary for a few years now

2022-03-08 08:57 UTC, closed without merging

2022-03-09 10:30 UTC, lehins commented
That is a very good question. The issue comes from the doctests needing ghc's env files. See how it is used on CI https://github.com/haskell/random/blob/c796015598f3eafaddaa9c79ec817ead3c55e936/.github/workflows/ci.yaml#L51-L52

In particular: `--write-ghc-environment-files=always`

So something like this should do the trick:

```shell
$ cabal configure --enable-tests
$ cabal build random:doctests --write-ghc-environment-files=always
$ cabal test random:doctests
```